# ~/Library/Rime/default.custom.yaml

patch:
  # 方案列表(即输入法列表)
  schema_list:
    - schema: double_pinyin_flypy # 小鹤双拼
    - schema: easy_en # 添加英文输入法
  
  style:
    horizontal: true            #  是否横排展示候选词

  menu:
    page_size: 9            # 候选词数量

  # 显示方案选单(即输入法列表)的快捷键
  switcher/hotkeys:
    # - Control+grave
    # - Control+Shift+grave
    # # Command需要写成Super，Option要写成Alt
    # - Super+Alt+grave
    # - Alt+Shift+grave
    # - Super+Control+grave
    - F4

  # 设置按左shift键上屏并切换到英文输入状态
  ascii_composer/switch_key/Shift_L: commit_code
  # 设置按右shift键上屏并切换到英文输入状态
  ascii_composer/switch_key/Shift_R: commit_code
