distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 1.0.2
install_time: "Tue Oct  3 13:10:15 2023"
installation_id: "c29bbe75-281d-46c2-a5ae-682ed0f84c4f"
rime_version: 1.11.2
update_time: "Mon Jun 10 04:03:07 2024"